name: openvswitch
version: 2.6.1
summary: Open vSwitch
description: |
  Open vSwitch is a production quality, multilayer, software-based,
  Ethernet virtual switch. It is designed to enable massive network
  automation through programmatic extension, while still supporting
  standard management interfaces and protocols (e.g. NetFlow, IPFIX,
  sFlow, SPAN, RSPAN, CLI, LACP, 802.1ag). In addition, it is designed
  to support distribution across multiple physical servers similar to
  VMware's vNetwork distributed vswitch or Cisco's Nexus 1000V.
grade: devel
confinement: strict

apps:
  switch:
    command: snap-wrapper $SNAP/share/openvswitch/scripts/ovs-ctl start --system-id=random
    stop-command: snap-wrapper $SNAP/share/openvswitch/scripts/ovs-ctl stop
    daemon: forking
    plugs:
      - network
      - network-bind
      - openvswitch-support
  ovs-vsctl:
    command: snap-wrapper $SNAP/bin/ovs-vsctl
    plugs:
      - network
  ovs-appctl:
    command: snap-wrapper $SNAP/bin/ovs-appctl
    plugs:
      - network
  ovs-ofctl:
    command: snap-wrapper $SNAP/bin/ovs-ofctl
    plugs:
      - network
  ovs-dpctl:
    command: snap-wrapper $SNAP/bin/ovs-dpctl
    plugs:
      - network

parts:
  openvswitch:
    source: http://openvswitch.org/releases/openvswitch-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: autotools
    build-packages:
      - libssl-dev
      - libnuma-dev
      - python-all
      - python-six
      - python-setuptools
    stage-packages:
      - uuid-runtime
    configflags: []
  wrapper:
    source: conf
    plugin: dump
    after:
      - openvswitch
